From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 235ebc2] Automated Server Update
 2 files changed, 13 insertions(+)
 create mode 100644 dailyserverlogfile.log
To https://github.com/cookeda/CapstoneSportsbook.git
   983b708..235ebc2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("./Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: './Data Collecting Src'
[main b22e7c9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   78a75c1..b22e7c9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6f86681] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b48dd0e..6f86681  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main b1f0102] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0035e5f..b1f0102  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 300a56d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   cc9fc99..300a56d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 77de77da] Automated Server Update
 2 files changed, 14 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   34b14411..77de77da  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 7186f7f5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   288e32a0..7186f7f5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main d5aa4cb5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   76186943..d5aa4cb5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1e3c28bf] Automated Server Update
 1 file changed, 9 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e50d317a..1e3c28bf  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 7571386c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ee88608a..7571386c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6e477ce9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fcf15881..6e477ce9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5c971fe1] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4deeba63..5c971fe1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 796a434e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0eb8705f..796a434e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6fd483dd] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   69c53831..6fd483dd  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f31b96e0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   bbf9d147..f31b96e0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c75a8b3c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   23248d0b..c75a8b3c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 31612210] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   627c916a..31612210  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a34410f7] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fd702158..a34410f7  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5080586e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ab15588d..5080586e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 85cedd1b] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8260abc9..85cedd1b  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main acb2a7e8] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9aceffbb..acb2a7e8  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3aa40f17] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   dc562c28..3aa40f17  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4c38cf94] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c13b2a7a..4c38cf94  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main acb0b5b1] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e306f159..acb0b5b1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4a500c1c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c826b884..4a500c1c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f81ecc59] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b1785bea..f81ecc59  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 2f4e4f42] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   148fc2cb..2f4e4f42  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 345592d2] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8b92c33e..345592d2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 78c29d25] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0cdff6f6..78c29d25  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3cd6073f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   2b95a9ad..3cd6073f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f40c27a1] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0807867b..f40c27a1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 434e839c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4a3ae257..434e839c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 9fd4d736] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d1ccd191..9fd4d736  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 224f3e97] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   5efe9816..224f3e97  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 8135b720] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   7f6fcc6d..8135b720  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main dbc406ed] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4610065f..dbc406ed  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a14edaf9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   60ae19be..a14edaf9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 2748716f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   44887ff9..2748716f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 98f4cdd8] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   58003d7a..98f4cdd8  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a4f87a14] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e76574fe..a4f87a14  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 86b08f32] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c10caa09..86b08f32  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main b515ec8c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   a7620bc2..b515ec8c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 43f9eb30] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   bfda57fe..43f9eb30  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3e80d0bb] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8b749ae5..3e80d0bb  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a8682ca3] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   cbdcbe06..a8682ca3  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1fda108a] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   6a027d59..1fda108a  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 69668458] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   488a7259..69668458  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main bdf0f400] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b2c54e4a..bdf0f400  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3760ad53] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e5442c2f..3760ad53  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a0eac588] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9c65686a..a0eac588  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 206314d1] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d23c1481..206314d1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c8d690d0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b6709e21..c8d690d0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main fea60b70] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   f2e1f9ef..fea60b70  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 017c8fea] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   3b774731..017c8fea  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 63, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
