From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 235ebc2] Automated Server Update
 2 files changed, 13 insertions(+)
 create mode 100644 dailyserverlogfile.log
To https://github.com/cookeda/CapstoneSportsbook.git
   983b708..235ebc2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("./Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: './Data Collecting Src'
[main b22e7c9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   78a75c1..b22e7c9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6f86681] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b48dd0e..6f86681  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main b1f0102] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0035e5f..b1f0102  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch            main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 300a56d] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   cc9fc99..300a56d  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 77de77da] Automated Server Update
 2 files changed, 14 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   34b14411..77de77da  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 7186f7f5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   288e32a0..7186f7f5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main d5aa4cb5] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   76186943..d5aa4cb5  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 1e3c28bf] Automated Server Update
 1 file changed, 9 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e50d317a..1e3c28bf  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 7571386c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ee88608a..7571386c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6e477ce9] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fcf15881..6e477ce9  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5c971fe1] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4deeba63..5c971fe1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 796a434e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0eb8705f..796a434e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 6fd483dd] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   69c53831..6fd483dd  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f31b96e0] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   bbf9d147..f31b96e0  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main c75a8b3c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   23248d0b..c75a8b3c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 31612210] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   627c916a..31612210  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main a34410f7] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   fd702158..a34410f7  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 5080586e] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   ab15588d..5080586e  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 85cedd1b] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8260abc9..85cedd1b  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main acb2a7e8] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   9aceffbb..acb2a7e8  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3aa40f17] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   dc562c28..3aa40f17  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4c38cf94] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c13b2a7a..4c38cf94  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main acb0b5b1] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   e306f159..acb0b5b1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 4a500c1c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   c826b884..4a500c1c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f81ecc59] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   b1785bea..f81ecc59  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 2f4e4f42] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   148fc2cb..2f4e4f42  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 345592d2] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   8b92c33e..345592d2  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 78c29d25] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0cdff6f6..78c29d25  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 3cd6073f] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   2b95a9ad..3cd6073f  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main f40c27a1] Automated Server Update
 2 files changed, 15 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   0807867b..f40c27a1  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 434e839c] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   4a3ae257..434e839c  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 9fd4d736] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   d1ccd191..9fd4d736  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
[main 224f3e97] Automated Server Update
 2 files changed, 13 insertions(+)
To https://github.com/cookeda/CapstoneSportsbook.git
   5efe9816..224f3e97  main -> main
From https://github.com/cookeda/CapstoneSportsbook
 * branch              main       -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 58, in <module>
    main()
  File "/media/myfiles/CapstoneSportsbook/Daily.py", line 12, in main
    os.chdir("media/myfiles/CapstoneSportsbook/Data Collecting Src")
FileNotFoundError: [Errno 2] No such file or directory: 'media/myfiles/CapstoneSportsbook/Data Collecting Src'
